apiVersion: v2
name: server-chart
description: A Helm chart to deploy the Challenge 3 Python server
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Haeyoon
    email: 19848408+HaeyoonJo@users.noreply.github.com