# Challenge 5: Complete this values file
#
# Define values for:
# - image: repository, tag, pullPolicy
# - replicaCount
# - service: type, port
# - resources (optional)
#
# Hint: The Python server listens on port 8080
replicaCount: 1

image:
  repository: orcahaeyoon/sre-interview-homwork
  tag: "challenge-3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi